spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/modu_cafe?serverTimezone=Asia/Seoul
    username: root
    password: root1234

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000
    open-in-view: false

logging:
  level:
    org.hibernate.type.descriptor.sql: trace